"""Emit a song library as Rust source for compiling into the frontend activity.

The device has no WASI filesystem, so charts can't be read at runtime — the whole
library is compiled in. This turns a list of `SongSpec`s into a
`songs_generated.rs` that defines a `SONGS` slice referencing the frontend's own
`song::{Song}` / `chart::{Chart, Note}` types.

The output is an *include fragment*: the frontend's build.rs `include!`s it into
`crate::song`, where `Song`, `Chart`, and `Note` are already in scope — so there
is no `use` line here.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .chart import Chart

_FILE_HEADER = """\
// @generated by boppo_chart — do not edit by hand.
// Song library ({count} song(s)).
//
// Include fragment: build.rs drops this into `crate::song`, where `Song`,
// `Chart`, and `Note` are already in scope (so there is no `use` here).
pub const SONGS: &[Song] = &[
"""

_FILE_FOOTER = "];\n"


@dataclass
class SongSpec:
    """One song for codegen: id, spoken-name clip, the audio it plays, its chart."""

    id: str
    audio_file: str
    chart: Chart
    name_audio: str = ""


def _chart_expr(chart: Chart, indent: str) -> str:
    """Render a `Chart { ... }` expression, each line prefixed with `indent`."""
    lines = [
        "Chart {\n",
        f"{indent}    bpm: {chart.bpm},\n",
        f"{indent}    lead_time_ms: {chart.lead_time_ms},\n",
        f"{indent}    hit_window_ms: {chart.hit_window_ms},\n",
        f"{indent}    notes: &[\n",
    ]
    for n in chart.notes:
        lines.append(
            f"{indent}        Note {{ lane: {n.lane}, hit_time_ms: {n.hit_time_ms} }},\n"
        )
    lines.append(f"{indent}    ],\n")
    lines.append(f"{indent}}}")
    return "".join(lines)


def songs_to_rust(specs: list[SongSpec]) -> str:
    parts = [_FILE_HEADER.format(count=len(specs))]
    for spec in specs:
        spec.chart.validate()
        parts.append("    Song {\n")
        parts.append(f'        id: "{spec.id}",\n')
        parts.append(f'        name_audio: "{spec.name_audio}",\n')
        parts.append(f'        audio_file: "{spec.audio_file}",\n')
        parts.append(f"        chart: {_chart_expr(spec.chart, '        ')},\n")
        parts.append("    },\n")
    parts.append(_FILE_FOOTER)
    return "".join(parts)


def write_songs_rust(specs: list[SongSpec], path: Path) -> None:
    path.write_text(songs_to_rust(specs))
